site_name: Tic-Tac-Toe 2 Docs
theme:
  name: material
nav:
  - Overview: index.md
  - Theory: theory.md
  - Datasets: datasets.md
  - Reproducibility: repro.md
  - Benchmarks: benchmarks.md
  - CLI Guide: cli.md
  - API Reference:
      - tictactoe: api/tictactoe.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
markdown_extensions:
  - admonition
  - toc:
      permalink: true
