site_name: Tic-Tac-Toe 2 Docs
site_url: https://romgenie.github.io/tic-tak-toe-2/
repo_url: https://github.com/romgenie/tic-tak-toe-2
theme:
  name: material
nav:
  - Overview: index.md
  - Theory: theory.md
  - Datasets: datasets.md
  - Data Card: data_card.md
  - Reproducibility: repro.md
  - Experiments: experiments.md
  - Results: results.md
  - Ablations: ablations.md
  - Benchmarks: benchmarks.md
  - CLI Guide: cli.md
  - API Reference:
      - tictactoe: api/tictactoe.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
markdown_extensions:
  - admonition
  - toc:
      permalink: true
