name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for PyPI trusted publishing
      contents: write  # for GitHub release
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Generate SBOM (CycloneDX)
        run: |
          python -m pip install cyclonedx-bom
          cyclonedx-py -o sbom.json || true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Export small dataset
        run: |
          python -m pip install .
          python -m tictactoe.cli datasets export --out data_raw/release_small --canonical-only --no-augmentation --epsilons 0.1 --format csv
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            data_raw/release_small/**
            requirements-lock.txt
            environment.yml
            conda-*.lock.*
            sbom.json
